version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./backend/database:/app/database
    expose:
      - "3001"
    restart: unless-stopped

  web:
    build:
      context: ./exam-system
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped